version: '3'

services:

  web-app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app
    command: >
      sh -c "python main.py"

